#!/bin/bash

# Script to fix Capacitor AGP version compatibility issues
# This script converts project dependencies to AAR dependencies for AGP 7.2.1 compatibility

echo "🔧 Fixing Capacitor AGP version compatibility..."

# Fix capacitor-cordova-android-plugins build.gradle
if [ -f "android/capacitor-cordova-android-plugins/build.gradle" ]; then
    echo "Patching capacitor-cordova-android-plugins/build.gradle..."
    sed -i 's/com.android.tools.build:gradle:8.0.0/com.android.tools.build:gradle:7.2.1/g' android/capacitor-cordova-android-plugins/build.gradle
    sed -i 's/JavaVersion.VERSION_17/JavaVersion.VERSION_11/g' android/capacitor-cordova-android-plugins/build.gradle
fi

# Fix capacitor.build.gradle
if [ -f "android/app/capacitor.build.gradle" ]; then
    echo "Patching app/capacitor.build.gradle..."
    sed -i 's/JavaVersion.VERSION_17/JavaVersion.VERSION_11/g' android/app/capacitor.build.gradle
fi

# Convert project dependencies to AAR dependencies in app/build.gradle
if [ -f "android/app/build.gradle" ]; then
    echo "Converting to AAR dependencies in app/build.gradle..."
    sed -i "s/implementation project(':capacitor-android')/implementation 'com.capacitorjs:capacitor-android:4.8.1'/g" android/app/build.gradle
fi

# Convert project dependencies to AAR dependencies in capacitor.build.gradle
if [ -f "android/app/capacitor.build.gradle" ]; then
    echo "Converting plugin dependencies to AAR format..."
    sed -i "s/implementation project(':capacitor-app')/implementation 'com.capacitorjs:capacitor-app:4.1.1'/g" android/app/capacitor.build.gradle
    sed -i "s/implementation project(':capacitor-device')/implementation 'com.capacitorjs:capacitor-device:4.1.0'/g" android/app/capacitor.build.gradle
    sed -i "s/implementation project(':capacitor-filesystem')/implementation 'com.capacitorjs:capacitor-filesystem:4.1.4'/g" android/app/capacitor.build.gradle
    sed -i "s/implementation project(':capacitor-haptics')/implementation 'com.capacitorjs:capacitor-haptics:4.1.0'/g" android/app/capacitor.build.gradle
    sed -i "s/implementation project(':capacitor-keyboard')/implementation 'com.capacitorjs:capacitor-keyboard:4.1.1'/g" android/app/capacitor.build.gradle
    sed -i "s/implementation project(':capacitor-network')/implementation 'com.capacitorjs:capacitor-network:4.1.0'/g" android/app/capacitor.build.gradle
    sed -i "s/implementation project(':capacitor-preferences')/implementation 'com.capacitorjs:capacitor-preferences:4.0.2'/g" android/app/capacitor.build.gradle
    sed -i "s/implementation project(':capacitor-splash-screen')/implementation 'com.capacitorjs:capacitor-splash-screen:4.2.0'/g" android/app/capacitor.build.gradle
    sed -i "s/implementation project(':capacitor-status-bar')/implementation 'com.capacitorjs:capacitor-status-bar:4.1.1'/g" android/app/capacitor.build.gradle
fi

# Clear the capacitor.settings.gradle to remove project references
if [ -f "android/capacitor.settings.gradle" ]; then
    echo "Clearing project references in capacitor.settings.gradle..."
    cat > android/capacitor.settings.gradle << 'EOF'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
// All Capacitor dependencies are now using AAR format for AGP 7.2.1 compatibility
// No project references needed
EOF
fi

echo "✅ Capacitor AGP compatibility patches applied!"
echo "✅ Converted all project dependencies to AAR format"
echo "Now try building your Android project in Android Studio."